services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}" # expose psql ports
    volumes:
      - pgdata:/var/lib/postgresql/data # for persistent data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER} # admin login
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD} # admin password
    ports:
      - "${PGADMIN_PORT_HOST}:${PGADMIN_PORT_CONTAINER}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin # for persistent pgadmin configs

  backend_app:
    build: frc_marketplace_API
    container_name: django_app
    command: >
      sh -c " pipenv run python manage.py makemigrations api && pipenv run python manage.py migrate api && pipenv run python manage.py runserver 0.0.0.0:${DJANGO_PORT_HOST}"
    ports:
      - "${DJANGO_PORT_HOST}:${DJANGO_PORT_CONTAINER}" # expose django ports
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT_CONTAINER}/${POSTGRES_DB}
      - DJANGO_SETTINGS_MODULE=frc_marketplace_API.settings # points to settings module
    depends_on:
      - db # waits for database to be ready
  
  frontend_app:
    build: vite-frontend
    container_name: vite_frontend
    ports:
      - "${VITE_PORT_HOST}:${VITE_PORT_CONTAINER}" # expose vite ports
    command: >
      sh -c "npm run dev -- --host"
    env_file:
      - .env

volumes:
  pgdata:
  pgadmin_data:
