from django.urls import path
from .views import (
    user_views,
    part_views,
    part_request_views,
    login_view,
    logout_view,
    get_logged_in_user_view,
    change_password_view,
    delete_user_view,
    user_by_team_number_view,
    request_view,
    request_edit_view,
    delete_request_view,
    sale_view,
    sale_edit_view,
    delete_sale_view,
    part_view,
    requests_by_part_view,
    sales_by_part_view,
    messages_by_user_get_view,
    message_by_id_get_view,
    message_post_view,
    requests_by_user_view,
    category_view,
    manufacturer_view,
    search_all_view,
    part_sale_views,
    dm_list_view,
    mark_messages_as_read,
)

urlpatterns = [
    path("users/", user_views, name="user_views"),
    path("users/self/", get_logged_in_user_view, name="get_logged_in_user_view"),
    path("parts/", part_views, name="part_views"),
    path("requests/", part_request_views, name="part_request_views"),
    path("requests/id/<str:request_id>/", request_view, name="request_view"),
    path("sales/id/<str:sale_id>/", sale_view, name="sale_view"),
    path("sales/id/<str:sale_id>/edit/", sale_edit_view, name="sale_edit_view"),
    path("sales/id/<str:sale_id>/delete/", delete_sale_view, name="delete_sale_view"),
    path("requests/id/<str:request_id>/edit/", request_edit_view, name="request_edit_view"),
    path("requests/id/<str:request_id>/delete/", delete_request_view, name="delete_request_view"),
    path("parts/id/<str:part_id>/", part_view, name="part_view"),
    path("parts/id/<str:part_id>/requests/", requests_by_part_view, name="part_requests_view"),
    path("parts/id/<str:part_id>/sales/", sales_by_part_view, name="part_sales_view"),
    path(
        "requests/user/<str:team_number>/",
        requests_by_user_view,
        name="part_request_views",
    ),
    path("login/", login_view, name="login_views"),
    path("logout/", logout_view, name="logout_views"),
    path("change-password/", change_password_view, name="change_password"),
    path("users/self/delete/", delete_user_view, name="delete_user_view"),
    path("users/frc<str:team_number>/", user_by_team_number_view, name="user_detail"),
    path(
        "message/<str:team_number>/",
        messages_by_user_get_view,
        name="messages_by_user_get_view",
    ),
    path(
        "message/id/<str:message_id>/",
        message_by_id_get_view,
        name="message_by_id_get_view",
    ),
    path("dms/", dm_list_view, name="dm_list_view"),
    path("messages/mark_as_read/", mark_messages_as_read, name="mark_messages_as_read"),
    path("message/", message_post_view, name="message_post_view"),
    path("parts/categories/", category_view),
    path("parts/manufacturers/", manufacturer_view),
    path("search/all/", search_all_view, name="search_all_view"),
    path("sales/", part_sale_views, name="part_sale_views"),
]
